### ISSUE TITLE
`context.actor` is `nil` in preparations and changes in `Transfer` resource, causing `KeyError`

### ISSUE THREAD

**Issue by kamaroly** [ash-project/ash_double_entry#54]
### Bug Description
When performing a `transfer` operation on the `Transfer` resource with an `actor` directly, it works as expected. However, `context.actor` is `nil` in a module preparation or change, resulting in the following error:

```ex
** (Ash.Error.Unknown) Unknown Error
     
     * %KeyError{key: :current_tenant, term: nil, message: "key :current_tenant not found in: nil\n\nIf you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map"}
       (kamaro 0.1.0) lib/my_app/preparations/set_tenant_from_actor.ex:5: MyApp.Preparations.SetTenantFromActor.prepare/3
       (ash 3.2.4) lib/ash/query/query.ex:704: anonymous fn/6 in Ash.Query.run_preparations/6
```

**How To Reproduce**

1. Define preparation

```ex
defmodule MyApp.Preparations.SetTenantFromActor do
  use Ash.Resource.Preparation

  def prepare(query, _opts, context) do
    Ash.Query.set_tenant(query, context.actor.current_tenant.domain)
  end
end
```

2. Define change 

```ex
defmodule MyApp.Changes.SetTenantFromActor do
  use Ash.Resource.Change

  def change(changeset, _opts, context) do
    Ash.Changeset.set_tenant(changeset, context.actor.current_tenant.domain)
  end

  def atomic(changeset, opts, context) do
    {:ok, change(changeset, opts, context)}
  end
end
```

3. Add them to your resource

```ex
defmodule MyApp.Ledger.Transfer do
  use Ash.Resource,
    domain: MyApp.Ledger,
    data_layer: AshPostgres.DataLayer,
    extensions: [AshDoubleEntry.Transfer]

  postgres do
    table "ledger_transfers"
    repo MyApp.Repo
  end

  preparations do
    prepare MyApp.Preparations.SetTenantFromActor
  end

  changes do
    change MyApp.Changes.SetTenantFromActor
  end

  multitenancy do
    strategy :context
  end

  actions do
    defaults [:read]
  end

  transfer do
    account_resource(MyApp.Ledger.Account)
    balance_resource(MyApp.Ledger.Balance)
  end
end
```

4. Attempt to transfer by passing an actor

```ex
MyApp.Ledger.transfer(account_1, account_2, actor: user)
```

**Expected behavior**
The `context.actor` should be properly set in preparations and changes so that the tenant can be accessed.

** Runtime

- Elixir version: 1.17.2
- Erlang version: Erlang/OTP 27
- OS: Ubuntu 24
- Ash version: {
- , "~> 3.2.0"}
- Related extension versions: {
- , "~> 1.0.3"}

**Comment by zachdaniel** [comment]
Thanks for the report. Please try `ash` `main`, the issue should be fixed there. Reopen this issue if it persists, 🙇
