### ISSUE TITLE
failure when deleting a transfer

### ISSUE THREAD

**Issue by tw4452852** [ash-project/ash_double_entry#7]
**Describe the bug**
When trying to delete a transfer, a failure will happen due to a foreign key constraint, here's the log:

```
  1) test delete (TransfersLiveTest)
     test/countbean_web/lives/transfers_test.exs:63
     ** (EXIT from #PID<0.22080.0>) an exception was raised:
         ** (Ash.Error.Unknown) Unknown Error

     * ** (Ecto.ConstraintError) constraint error when attempting to delete struct:

         * "balances_transfer_id_fkey" (foreign_key_constraint)

     If you would like to stop this constraint violation from raising an
     exception and instead add it as an error to your changeset, please
     call `foreign_key_constraint/3` on your changeset with the constraint
     `:name` as an option.

     The changeset defined the following constraints:

         * "transfers_pkey" (unique_constraint)

       (ecto 3.11.1) lib/ecto/repo/schema.ex:815: anonymous fn/4 in Ecto.Repo.Schema.constraints_to_errors/3
       (elixir 1.15.7) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
       (ecto 3.11.1) lib/ecto/repo/schema.ex:799: Ecto.Repo.Schema.constraints_to_errors/3
       (ecto 3.11.1) lib/ecto/repo/schema.ex:780: Ecto.Repo.Schema.apply/4
       (ecto 3.11.1) lib/ecto/repo/schema.ex:571: anonymous fn/13 in Ecto.Repo.Schema.do_delete/4
       (ash_postgres 1.3.64) lib/data_layer.ex:2178: AshPostgres.DataLayer.destroy/2
       (ash 2.17.9) lib/ash/actions/destroy.ex:328: anonymous fn/9 in Ash.Actions.Destroy.as_requests/5
       (ash 2.17.9) lib/ash/changeset/changeset.ex:2209: Ash.Changeset.run_around_actions/2
       (ash 2.17.9) lib/ash/changeset/changeset.ex:1808: anonymous fn/3 in Ash.Changeset.with_hooks/3
       (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.6.0) lib/db_connection.ex:1710: DBConnection.run_transaction/4
       (ash 2.17.9) lib/ash/changeset/changeset.ex:1806: anonymous fn/3 in Ash.Changeset.with_hooks/3
       (ash 2.17.9) lib/ash/changeset/changeset.ex:1936: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
       (ash 2.17.9) lib/ash/changeset/changeset.ex:1787: Ash.Changeset.with_hooks/3
       (ash 2.17.9) lib/ash/actions/destroy.ex:303: anonymous fn/9 in Ash.Actions.Destroy.as_requests/5
       (ash 2.17.9) lib/ash/engine/request.ex:1111: Ash.Engine.Request.do_try_resolve_local/4
       (ash 2.17.9) lib/ash/engine/request.ex:284: Ash.Engine.Request.do_next/1
       (ash 2.17.9) lib/ash/engine/request.ex:213: Ash.Engine.Request.next/1
       (ash 2.17.9) lib/ash/engine/engine.ex:712: Ash.Engine.advance_request/2
       (ash 2.17.9) lib/ash/engine/engine.ex:637: Ash.Engine.fully_advance_request/2
             (ash 2.17.9) lib/ash/error/error.ex:524: Ash.Error.choose_error/2
             (ash 2.17.9) lib/ash/error/error.ex:252: Ash.Error.to_error_class/2
             (ash 2.17.9) lib/ash/actions/destroy.ex:148: Ash.Actions.Destroy.do_run/4
             (ash 2.17.9) lib/ash/actions/destroy.ex:37: Ash.Actions.Destroy.run/4
             (ash 2.17.9) lib/ash/api/api.ex:2221: Ash.Api.destroy!/3
             (countbean 0.1.0) lib/countbean_web/live/transfer_live/index.ex:101: CountbeanWeb.TransferLive.Index.handle_event/3
             (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:487: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
             (telemetry 1.2.1) /home/tw/code/countbean/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
             (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:246: Phoenix.LiveView.Channel.handle_info/2
             (stdlib 5.1.1) gen_server.erl:1077: :gen_server.try_handle_info/3
             (stdlib 5.1.1) gen_server.erl:1165: :gen_server.handle_msg/6
             (stdlib 5.1.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3

```

You could reproduce this issue using the default transfer live generated by `mix ash_phoenix.gen.live API Transfer`, and click the delete button on the web. 

After a quick look at the `lib/transfer/changes/verify_transfer.ex`, I think we should handle the destroy action properly.

**Comment by zachdaniel** [comment]
I think at the current moment it's not accounting for deleting transfers, but there isn't a reason that we can't account for it. We'll need to first delete any balances associated with that, and then verify the balances again.

**Comment by zachdaniel** [comment]
Just pushed a new version that supports destroying transfers. Something we don't currently support (and may not ever support?) is updating transfers. Although...we can support it potentially as long as the amount, to or from account id isn't changing...will do that later.

**Comment by zachdaniel** [comment]
Alright, pushing a new version that support modifying fields aside from the source/destination of the transfer, the amount, or the id.

**Comment by tw4452852** [comment]
nice👍 thanks @zachdaniel
